### ISSUE TITLE
Allow the use of JS files to configure things

### ISSUE THREAD

**Issue by yihangho** [simov/express-admin#134]
I'm not sure if this has been discussed/considered before. Currently, the configuration files (`config.json`, `settings.json`, `custom.json`, and `users.json`) _have_ to be JSON files since they are [hardcoded](https://github.com/simov/express-admin/blob/7b7e898b0d188b6f54b79ac234622f37ec64c228/app.js#L302-L305) as such in the codebase.

This has some limitations - the most important one being they are static. For example, it is quite common for us to configure the database credentials using environment variables. This will not be possible with JSON files. My current solution to this is to generate these JSON files right before starting express admin. (Think of this as running `generateJsonFile && admin config`.)

I think this is suboptimal. My proposal here is to accept JS files _in addition to_  JSON files.

Pros:
1. Allows various configuration options to be set dynamically (e.g., the database credential issue I mention here).
2. Opens up new possibilities for the kind of things that we can do with express-admin. For example, we can add functions to `settings.js` to allow arbitrary formatting of data or even dynamically generated data. For example:

    - If we store an enum as an integer column (such as 0 = male, 1 = female), we can have a, say, formatter function that maps a raw value into a human-friendly string.

Cons:
1. There _might_ be some backward-incompatibility issue. We can fix this by making the JS config files strictly opt-in. (For e.g., enabled by a command line flag or always read JSON files if they are present.)

If this is something that the maintainers are willing to consider, I'm happy to come up with a prototype to get things started. 😃

**Comment by Hillshum** [comment]
Just doing `require(path.join(args.dpath, 'config')`, leaving off the extension, would allow JS files that export a config object. Literally no other changes needed.

**Comment by tilomitra** [comment]
Any update on this?

**Comment by simov** [comment]
Check out the [embedding](https://simov.github.io/express-admin/#embedding) section of the docs.

**Comment by simov** [comment]
Hi, check out v2 of the admin. In v2 the admin is simply an Express.js [middleware](https://github.com/simov/express-admin#middleware). Also, a little bit down below I am explaining exactly about that case and the fact that only the `settings.json` is required to be a file stored on your server, but then even that can now be manipulated before passing as an object to the middleware, even though I don't know how useful that would be. But for the rest of the config, in particular the `config` and the `users` key it is actually recommended to load that from an external storage since that contains your password for the database connection and for your admin users respectively.

Also have a look at the [changelog](https://github.com/simov/express-admin/blob/main/CHANGELOG.md#change-log) for any potential breaking changes, all are pretty minor.
